added Soundeffects
RoboArenaDrolf/RoboArenaDroelf.github.io pull request #44
Opened 2024-07-06 11:13 UTC by ManuShift

added following soundeffects:

- jumping-sound
- death-sound
- damage-sound

2024-07-09 19:54 UTC, DerApplaudeur commented on src/arena.py
> +    blocks_base_path = "Tiles/"
This breakes the map/tile loading

2024-07-09 19:58 UTC, DerApplaudeur requested changes
every single file link is broken for me.
The sounds are nice but we should add an option to change the volume soon.
You also changed the 2 shots ranged attack into a single shot attack wihtout mentioning it in a commit message or a comment.

2024-07-09 20:05 UTC, DerApplaudeur commented on src/game.py
> -                    player_robot.ranged_attack()
This was used for the second shot

2024-09-03 11:16 UTC, Luceleven commented
Deprecated

2024-09-03 11:16 UTC, closed without merging